### ISSUE TITLE
Has anyone tried PADD with Pi-hole v5?

### ISSUE THREAD

**Issue by christianboyle** [jpmck/PADD#102]
Wondering if any brave souls have attempted to use PADD with Pi-hole v5 yet.   
  
Any issues?   
  
Flawless install?  
  
Word is it's not easy to roll back to v4 due to the DB changes in v5.

**Comment by downtime0** [comment]
I've had no issues with PADD v3.0.2 after updating to pi-Hole v5. Go for it!
However PADD v3.1 has a number of bugs in it so I recommend staying on v.3.0.x until the next minor v3.1.1 release.

**Comment by downtime0** [comment]
@christianboyle hey I just implemented both your suggested code commits for v3.1 in my own file. Nice job on that. The fix for CleanEcho() was just what i was looking for. ...that and the fix for "padd_version_latest"

**Comment by christianboyle** [comment]
![](https://user-images.githubusercontent.com/1605754/82714373-e23ba600-9c53-11ea-9a24-83a34d552fbb.jpg)

![](https://user-images.githubusercontent.com/1605754/82714528-b7058680-9c54-11ea-9b41-a9ab53584563.png)

Good stuff! Can confirm that stuff works well, haven't experienced any issues since I switched to using my [PR fork](https://github.com/jpmck/PADD/pull/85) (72d uptime, ellipsis works, etc.).   
  
Another issue thread has another set of fixes that includes [my fixes and others](https://github.com/jpmck/PADD/issues/86#issuecomment-598746643), which results in a more [full use of the display](https://github.com/jpmck/PADD/issues/86#issuecomment-597851806). Only issue seems to be the Memory bar not lining up with the CPU Temp.

**Comment by downtime0** [comment]
Before last week's pi-Hole v5 update, mine was stable running like 100+ days as well.
...and today the clock starts over gain with PADD update.
![PADD screenshots compared 2020-05-22](https://user-images.githubusercontent.com/17791278/82718212-fb455680-9c55-11ea-893f-5ef3e945ca77.jpg)

Thanks for the link to the other thread, it didn't look like it was doing much more than I already had in my local file.

**Comment by christianboyle** [comment]
That looks ace, any chance you could share your padd.sh?

**Comment by downtime0** [comment]
here you go.
[padd.sh.txt](https://github.com/jpmck/PADD/files/4670989/padd.sh.txt)

**Comment by christianboyle** [comment]
thanks sir!
