### ISSUE TITLE
Faulty Screendetection in 3.2

### ISSUE THREAD

**Issue by Gothico74** [jpmck/PADD#108]
After upgrade to PADD 3.2 the screen on my raspberry is teared up
way too much "="
TFT is 3.5 inch
Last padd 3.1 was working perfect with the two community fixes

![padd_3_2](https://user-images.githubusercontent.com/57674557/86510087-17a7e780-bded-11ea-9b17-a1c7c8a0391a.gif)

**Comment by LPanic** [comment]
yup. having the exact same issue since update.

**Comment by LPanic** [comment]
Is there a way to downgrade to the previous version?

**Comment by derekschinke** [comment]
Same issue.

**Comment by Gothico74** [comment]
> 
> 
> Is there a way to downgrade to the previous version?

https://github.com/jpmck/PADD/releases

**Comment by GorramRob** [comment]
I diffed 3.1 and 3.2, it looks like the issue may be line 860.

I commented it out and have not observed any problems so far, both on a similar pi screen to what is being used in the OP picture and on a normal terminal.

**Comment by jpmck** [comment]
Fixed in v3.2.1.
