### ISSUE TITLE
Using FTL version reply with out-of-date

### ISSUE THREAD

**Issue by Jacopx** [jpmck/PADD#19]
**Describe the bug**
Using FTL version of PiHole reply with out-of-date in the first part of PADD

**Expected behavior**
My system is up-to-date in the FTL branch, I'm expecting to see: "up-to-date"

**Screenshots**
<img width="535" alt="screenshot 2018-06-25 11 15 02" src="https://user-images.githubusercontent.com/14002538/41841722-53aa5504-7869-11e8-9c24-f0e382632f98.png">

**Comment by ferazambuja** [comment]
https://github.com/jpmck/PADD/issues/17

We will have to wait for the next release

**Comment by jpmck** [comment]
This will not be implemented at this time.

(Please see [Issue #15](https://github.com/jpmck/PADD/issues/15#issuecomment-390474893).)
