### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by jonsy777** [jpmck/PADD#23]
**Is your feature request related to a problem? Please describe.**

When using cloudlflare's DNS over HTTPS, the built in "DNS Server" list in pi hole (web interface, config file, etc) goes blank. This leads to the list of DNS servers in PADD to appear blank.

**Describe the solution you'd like**
If there was a way to indicate that DNS over HTTPS was in fact being used, as well as indicate what DNS servers were being used within DNS over HTTPS, that would be awesome. 

**Describe alternatives you've considered**
I haven't really found a workaround/way to make this work. Because DNS over HTTPS is somewhat under the hood of pi-hole, I haven't really messed with it.

**Additional context**
I know it has a config file that contains the DNS on the end of DNS over HTTPS so that might be a way to grab the info there. (although i have minimal coding knowledge.)

**Comment by p1r473** [comment]
I can't imagine the latency of DNS over HTTPS
Have you considered dnscrypt-proxy instead?

**Comment by jpmck** [comment]
It is my understanding that using `cloudflared` will result in you using `127.0.0.1#5053` as your "upstream" DNS server. PADD checks for this and will display "Cloudflare" if this is the case.
