### ISSUE TITLE
padd VS the chronometer

### ISSUE THREAD

**Issue by maserowik** [jpmck/PADD#28]
I appear to be having a slight issues
i have padd installed and it is giving me data that appears incorrect with the chronometer

![padd](https://user-images.githubusercontent.com/25713782/43370374-f833277a-934b-11e8-80c7-2bce536742c5.PNG)

thanks
Mike

**Comment by jpmck** [comment]
I believe this was resolved with #37.

Can you confirm that this is fixed?

**Comment by jpmck** [comment]
Closing for now.
