### ISSUE TITLE
PADD on osmc

### ISSUE THREAD

**Issue by xxcriticxx** [jpmck/PADD#29]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
errors when running PADD on osmc pihole Pi-hole Version v4.0 Web Interface Version v4.0 FTL Version v4.0  

**To Reproduce**
1. install PADD 
2. run PADD

**Expected behavior**
see correct output

**Screenshots**
![capture](https://user-images.githubusercontent.com/15007183/43716037-9611e8c8-9950-11e8-9538-0872a90b183c.PNG)

**Additional context**
i am running this on old apple tv 1

**Comment by jpmck** [comment]
Thanks @xxcriticxx.

This was fixed with [Pull Request #35](https://github.com/jpmck/PADD/pull/35) and will be part of the upcoming release.
