### ISSUE TITLE
System agnostic CPU core count - tested on Pine64

### ISSUE THREAD

**Issue by atiensivu** [jpmck/PADD#33]
**Describe the bug**
Divide by 0 error because the string in /proc/cpuinfo does not exist outside of Raspberry Pi

**To Reproduce**
1. Run PADD on a non-Pi device - in my case, a Pine64 

**Expected behavior**
Correct corecount

**Additional context**
I fixed it by using the /sys tree version of cpu count - hopefully this is usable on most kernels 

Code change:

# CORES
#coreCount=$(grep -c 'model name' /proc/cpuinfo)
declare -i coreCount=1
coreCount=$(cat /sys/devices/system/cpu/kernel_max 2> /dev/null)+1

This works for me - reports 4 cores which is correct. 

https://github.com/atiensivu/PADD/tree/atiensivu-patch-1

**Comment by jpmck** [comment]
Thanks Aaron and Tim! I made a PR for this and it will be in the next release.
