### ISSUE TITLE
PI Padd Display shuts off after 30 minutes

### ISSUE THREAD

**Issue by R3clu23** [jpmck/PADD#34]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**

**To Reproduce**
1. ...Reboot Pi 
2. ... Wait 30 minutes display goes blank

**Expected behavior**
After 30 minutes of pi being online, the PiPadd display goes blank. I've already check the /etc/kbd/config and /etc/rc.local file to see if any of the setting were incorrect.  

I followed the following guide here:
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/console-configuration#turn-off-console-blanking-5-10

I also have a document with my config and rc.local setting here:
https://drive.google.com/open?id=1-dliNG9lo78wvywe6_61X3wFimcXeJ6m
**Screenshots**
I have two screen shots here 
Before:
https://imgur.com/GCt9j1z
After 30 minutes:
https://imgur.com/EZnxfWf
**Additional context**
I have also posted a thread on reddit about this issue here:
https://www.reddit.com/r/pihole/comments/9tktc5/pihole_and_pi_padd/

**Comment by jpmck** [comment]
This is beyond the scope of the project and isn't indicative of a problem with PADD, but with the configuration of your Raspberry Pi / PiTFT.

Unfortunately, I'm unable to fix this.
