### ISSUE TITLE
Screen won't sleep....

### ISSUE THREAD

**Issue by Andymc1280** [jpmck/PADD#36]
Simply put, my display is permanently on, even after editing crontab and adding:

``#PADD Sleep Turn off the PiTFT+ at midnight

00 00 * * * sh -c 'echo "0" > /sys/class/backlight/soc:backlight/brightness'
#Turn on the PiTFT+ at 8:00 am
00 08 * * * sh -c 'echo "1" > /sys/class/backlight/soc:backlight/brightness''

**Comment by Andymc1280** [comment]
`PADD Sleep Turn off the PiTFT+ at midnight

00 00 * * * sh -c 'echo "0" > /sys/class/backlight/soc:backlight/brightness'
Turn on the PiTFT+ at 8:00 am

00 08 * * * sh -c 'echo "1" > /sys/class/backlight/soc:backlight/brightness'
PiTFT+ SLEEPY TIME Turn off the PiTFT+ at midnight

00 00 * * * sh -c 'echo "0" > /sys/class/backlight/soc:backlight/brightness'
Turn on the PiTFT+ at 8:00 am

00 08 * * * sh -c 'echo "1" > /sys/class/backlight/soc:backlight/brightness'`

**Comment by jpmck** [comment]
This beyond the scope of this project.

(See Adafruit's [documentation](https://learn.adafruit.com/adafruit-pitft-3-dot-5-touch-screen-for-raspberry-pi/backlight-control) for more information on setting up your screen.)
