### ISSUE TITLE
line 265: [[: 8+: syntax error: operand expected (error token is "+")

### ISSUE THREAD

**Issue by sheeeng** [jpmck/PADD#43]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*
<img width="682" alt="screen shot 2019-02-10 at 17 20 04" src="https://user-images.githubusercontent.com/305414/52536250-4afd5880-2d58-11e9-9bce-7583ce88b740.png">

**Describe the bug**
Below error was shown.
```text
./padd.sh: line 265: [[: 8+: syntax error: operand expected (error token is "+")
```

**To Reproduce**
1. Run padd.sh script.

**Expected behavior**
No errors shown.

**Screenshots**
See attached image.

**Comment by captcarl13** [comment]
I have this same issue. Error also appears when PADD is running, see attached.
<img width="542" alt="screen shot 2019-02-10 at 11 39 38" src="https://user-images.githubusercontent.com/867543/52536442-a6afed80-2d28-11e9-8875-08beea5155e4.png">
