### ISSUE TITLE
Screen on 3.5" TFT is crap after updating

### ISSUE THREAD

**Issue by todrees1967** [jpmck/PADD#48]
**Describe the bug**
After updating to the latest version of PADD the screen is totally crap on my 3.5" TFT display

**To Reproduce**
1. ... uopdate to the latest version
2. ...

**Screenshots**
See attached.

![padd](https://user-images.githubusercontent.com/24406702/53074693-b4fdc680-34eb-11e9-8541-0722951cb4ea.jpg)

**Comment by tspotz** [comment]
update again, fixed in latest version

**Comment by todrees1967** [comment]
still looks the same, also after updating again!

**Comment by C44Supra** [comment]
Same issue here!

**Comment by jpmck** [comment]
Can you run `tput cols && tput lines` from your pi iteself (by hooking a keyboard up to it, not from sshing into it from another machine)?

**Comment by C44Supra** [comment]
> Can you run `tput cols && tput lines` from your pi iteself (by hooking a keyboard up to it, not from sshing into it from another machine)?

That outputs:
`60
20`

**Comment by jpmck** [comment]
Thanks for checking @C44Supra.

Fixed with d1d6cec9b6cc8765dc64bb4bd624b5f7143cef80.

Please update your PADD.
