### ISSUE TITLE
Route: command not found

### ISSUE THREAD

**Issue by hasecbinusr** [jpmck/PADD#52]
**Describe the bug**
Updated raspberry pi with apt-get update and apt-get upgrade and updated PADD to v. 3.0.2.  Now PADD generates the error `./padd.sh: line 263: route: command not found`.

**To Reproduce**
1. Update working pi-hole system.
2. Update PADD.

**Expected behavior**
Expected error-free performance as prior to upgrade.

**Screenshots**
<img width="438" alt="screen shot 2019-03-07 at 1656 17" src="https://user-images.githubusercontent.com/26094353/53995250-26e42b80-40fa-11e9-97b4-96eb0358bfb9.png">

**Additional context**
This might be fixed as discussed in PR #50.

**Comment by hasecbinusr** [comment]
Changed line 263 as PR #50 commit and operation is error-free again.

**Comment by jpmck** [comment]
Corrected in #50. Thanks @tom472. This was added to v3.1.
