### ISSUE TITLE
Date/Time info in PADD

### ISSUE THREAD

**Issue by misanthrophy** [jpmck/PADD#55]
Hi,

is there any chance to add the date/time in the overview section?

I for myself for example do not need this information:

CPU Load: 0.21, 0.17, 0.12

This is enough for me:
CPU Load: [■·········] 6.2% 

So replacing the upper information with the time is "more important" for me. Or if thats not an option for another release, can you tell me, if it is possible to change some code lines to reflect my request on my own system? :) 

Thx in advance!

**Comment by jpmck** [comment]
I don't usually need to know what time it is when I look at my Pihole... and don't foresee changing that anytime soon. But I can see why you'd like it there.

The function ```PrintSystemInformation()``` [near line 710](https://github.com/jpmck/PADD/blob/master/padd.sh#L710) is where the CPU load is printed.

Specifically, you'll be looking for the line(s) that end with ```"CPU Load:" "${cpu_load[0]}" "${cpu_load[1]}" "${cpu_load[2]}"```, which is where the CPU load (that you don't want) is coming from.

Replacing that bit with something like ```$(date +%m-%d-%Y %H:%M)``` would give you ```5-21-19 20:42```.
