### ISSUE TITLE
Custom PADD CLI resolution?

### ISSUE THREAD

**Issue by cmdshft** [jpmck/PADD#57]
Is there a way to define a custom layout for PADD on the Hyperpixel 4 display? I'd love to have the size of this:
![UOzaIQi](https://user-images.githubusercontent.com/8571823/56709017-05142780-66ed-11e9-8828-363c290ebb73.jpg)

But with the layout like this (logo, health status, versions at the top):

![wgekLzU](https://user-images.githubusercontent.com/8571823/56709027-12c9ad00-66ed-11e9-9903-4966b83220eb.jpg)

I have tried all the options in dpkg-reconfigure console-setup and nothing feels right.

**Comment by cmdshft** [comment]
Any info on this?

**Comment by cmdshft** [comment]
Bump. Is there no way to get the display to fit the "Mega" output to the 4" size?

**Comment by jpmck** [comment]
I don't understand. You want a custom set-up based on the second photo of the setup that already exists?

**Comment by cmdshft** [comment]
No, I want to use the Mega size in a way that will fill the entire display on the 4" Hyperpixel I have install.

![padd](https://user-images.githubusercontent.com/8571823/58139437-9bfad380-7c08-11e9-9756-685f0edbcdaf.jpg)

**Comment by jpmck** [comment]
Unfortunately I don't have any plans for developing any other sizes for PADD anytime soon, and developing a different one for each type of display that everyone is using would be close to impossible.

If you want, you can tweak the output as you see fit. The functions all follow the same naming convention: ```PrintSection``` (i.e. ```PrintNetworkInformation```). If you want to make a pull request to add your changes to the project, feel free.

**Comment by myusuf3** [comment]
has anyone gotten this working? I am also running hyperpixel 4.
