### ISSUE TITLE
Odd Timestamp

### ISSUE THREAD

**Issue by cmdshft** [jpmck/PADD#58]
Seeing odd time stamp in PADD display. Photos are taken several minutes apart. Any fix for this?

![IMG_1486](https://user-images.githubusercontent.com/8571823/57171061-f0b3e700-6dde-11e9-8376-d3a0e97ee7db.jpg)
![IMG_1487](https://user-images.githubusercontent.com/8571823/57171062-f0b3e700-6dde-11e9-98ec-7d55f9be5cda.jpg)
![IMG_1488](https://user-images.githubusercontent.com/8571823/57171063-f0b3e700-6dde-11e9-87f5-b00ea8bd652c.jpg)

**Comment by jpmck** [comment]
This should be corrected. Thanks @danmurry!
