### ISSUE TITLE
Overfills screen..

### ISSUE THREAD

**Issue by Jeffmc1** [jpmck/PADD#68]
I have PADD Running on a 3.5" Pi TFT screen.. when it runs the TOP few lines scroll off (see pic) is there something I should change somewhere ?
![20191017_003819](https://user-images.githubusercontent.com/56575190/66988048-be3d3400-f076-11e9-8a94-f095bb3614ec.jpg)

**Comment by Jeffmc1** [comment]
Although when running it in PUTTY (SSH On Win) it looks different....
![20191017_004337](https://user-images.githubusercontent.com/56575190/66988394-4d4a4c00-f077-11e9-9b98-44d0cd7f9229.jpg)

**Comment by ferazambuja** [comment]
Is the screen resolution. Try to make the putty screen smaller and you will see that it adapts.
You can find more info on the wiki https://github.com/jpmck/PADD/wiki/Sizes

**Comment by jpmck** [comment]
The PADD Slim photo that you attached is exactly what the display should look like. No lines are being cut off. You can resize the font being used as mentioned by @ferazambuja and as described under the [Setup](https://github.com/jpmck/PADD/wiki/Setup) portion of the Wiki. (See the last two bullets.)

![PADD](https://jpmck.com/img/padd/5slim.png)

**Comment by derekschinke** [comment]
FYI, I'm having an actual screen overfill issues with 3.1. Every font size I've tried results with the PADD logo being off screen, along with current version information.
