### ISSUE TITLE
Glitch while using pi-hole Beta

### ISSUE THREAD

**Issue by WildHunterz** [jpmck/PADD#93]
Hi there,

the Display glitches out the range when using the Beta of PiHole caused by the version-numbers.
Any workarround available?

![IMG_0410](https://user-images.githubusercontent.com/40420616/78438978-a2a30580-7677-11ea-855d-42b3b670c406.jpg)
![padd1](https://user-images.githubusercontent.com/40420616/78438992-a33b9c00-7677-11ea-9b5a-7cabc69ac8fe.JPG)

**Comment by jpmck** [comment]
> _Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!_

You’re free to modify the code on your install, but there are no plans to have PADD support beta versions of Pi-hole.

**Comment by WildHunterz** [comment]
Thanks for your reply.
Could u give me a hint where to modify the padd.sh?

**Comment by jpmck** [comment]
The `PrintLogo()` function might be the easiest place to look. (I’m on my phone so I don’t have the line number handy.)
