### ISSUE TITLE
Console screen of PADD in portrait need to rotate..

### ISSUE THREAD

**Issue by Jeffmc1** [jpmck/PADD#98]
![20200425_141414](https://user-images.githubusercontent.com/56575190/80292364-24cc9a00-870b-11ea-8119-fe1dc6bc9adf.jpg)

im running a pimoroni(Screen) on a Pi4 w/ raspbian and PIHOLE and PADD ? my PADD display is what looks like a console and its running in PORTRAIT Mode and I need to change it to Landscape mode....... Anyone suggestions ?

When I installed Raspbian i had to goto prefs and change it to rotate LEFT and it showed up fine (landscape)

I installed raspbian
installed pimoroni LCD Drivers
Installed PADD
Setup padd to autorun/autologin etc
but console is rotated to the RIGHT by 90 degrees.....

It is in portrait mode I need to rotate it LEFT 90 to landscape :)

**Comment by downtime0** [comment]
This is probably more of issue with your LCD Display driver. Check your display install instructions for a config file parameter to rotate screen either 90 or 270 degrees. 
I used these drivers --> https://github.com/goodtft/LCD-show  and the "MHS35B-show" driver
but try a few different ones until you find one that works best with your model.
